GMCプラグインとルーティングが競合する問題を修正
EC-CUBE/sitekit-plugin pull request #5
Opened 2021-09-08 08:34 UTC by chihiro-adachi

2021-09-08 08:46 UTC, kiy0taka requested changes

2021-09-08 08:46 UTC, kiy0taka commented on PluginManager.php
> +    public function update(array $meta, ContainerInterface $container)
一度連携したあとはサイト認証は不要なのでファイルがあってもルーティングを追加する必要はないです。
再連携するときも新しい認証ファイルを生成するのでこの処理は不要です。

2021-09-08 23:18 UTC, chihiro-adachi commented on PluginManager.php
> +    public function update(array $meta, ContainerInterface $container)
@kiy0taka 
ありがとうございます。修正しました。

2021-09-09 00:11 UTC, kiy0taka approved these changes

2021-09-09 00:12 UTC, merged